### ISSUE TITLE
Project Not Building - Dependecy Broken - github.com/lestrrat-go/jwx/v2

### ISSUE THREAD

**Issue by gamer31dev** [iden3/iden3comm#38] opened 2023-11-04 20:14 UTC
Dependecy github.com/lestrrat-go/jwx/v2 doesn't exist any more.
I think the owner of that repository changed moved it into the next branch.
For this reason I cant Build PolygonID Issuer Node....

**Comment by ilya-korotya** [comment] 2023-11-06 11:51
Hi, @gamer31dev. Thank you for reporting the issue. Could you check if you can run the Issuer node now, please? I attempted to download github.com/lestrrat-go/jwx/v2 using the command go get github.com/lestrrat-go/jwx/v2, and it worked for me. It's possible that you experienced a GitHub or network connection issue. Please try again, and let me know if you face any problems.

**Comment by gamer31dev** [comment] 2023-11-06 20:03
Hi, @ilya-korotya, Thanks for the fast reply.
I've tried **go get github.com/lestrrat-go/jwx/v2** and you are right, it downloaded **github.com/lestrrat-go/jwx v1.2.26**
So basically, 
In the go.mod file it was previously this record:
github.com/lestrrat-go/jwx/v2 v2.0.9-0.20230429214153-5090ec1bd2cd
and after your command it changed it to : 
github.com/lestrrat-go/jwx v1.2.26

I think the problem is that when there is a specific revision specified in the go.mod like this : 
https://github.com/0xPolygonID/issuer-node/blob/main/go.mod

then it return the error : 

go get github.com/lestrrat-go/jwx/v2
go: github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd: invalid version: unknown revision 5090ec1bd2cd

**Comment by ilya-korotya** [comment] 2023-11-07 10:52
Hm. It is strange behaviour. Since v2 suffix should download some v2.*.* version.
For me, it's works differently:
```bash
illia@Polygon-HNGQ777T99 identity-server % go get github.com/lestrrat-go/jwx/v2
go: upgraded github.com/lestrrat-go/blackmagic v1.0.1 => v1.0.2
go: upgraded github.com/lestrrat-go/jwx/v2 v2.0.12 => v2.0.16 // I have v2 instead of v1.2.26
go: upgraded golang.org/x/crypto v0.12.0 => v0.14.0
go: upgraded golang.org/x/sys v0.11.0 => v0.13.0
go: upgraded golang.org/x/text v0.12.0 => v0.13.0
**illia@Polygon-HNGQ777T99 identity-server % go get github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd
go: removed github.com/iden3/iden3comm/v2 v2.0.0
go: downgraded github.com/lestrrat-go/jwx/v2 v2.0.16 => v2.0.9-0.20230429214153-5090ec1bd2cd // this commit hash is available for me
```
Could you check our golang version, please? I'm using `go version go1.20.2 darwin/arm64`

**Comment by gamer31dev** [comment] 2023-11-07 21:02
@ilya-korotya 
Im using this version on Amazon Linux
go version go1.20.10 linux/amd64

**Comment by ilya-korotya** [comment] 2023-11-09 23:36
Hi, @gamer31dev.
Could you please try using the [Dockerfile](https://github.com/0xPolygonID/issuer-node/blob/main/Dockerfile) to set up the issuer node in your environment? I'm unable to reproduce the bug.

**Comment by ilya-korotya** [comment] 2023-11-09 23:40
I see that you have opened the same [issue](https://github.com/0xPolygonID/issuer-node/issues/519) in the issuer-node repository. I will close this one. Please reopen it if you need to.

**Closed by ilya-korotya** 2023-11-09 23:40 UTC
